"""add_reminder_minutes_to_tasks

Revision ID: c668362e44a6
Revises: 03ce87391ab1
Create Date: 2026-09-19 17:59:21.120152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c668362e44a6'
down_revision: Union[str, Sequence[str], None] = '03ce87391ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_minutes')
    # ### end Alembic commands ###
